import localFont from "next/font/local";
import "./globals.css";

// import Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import ThemeProvider
import { ThemeProvider } from "@/components/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`min-h-screen antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
